### ISSUE TITLE
Unavailable sensor inside card crashes whole view

### ISSUE THREAD

**Issue by jacekpaszkowski** [dnguyen800/air-visual-card#15]
Hi,

I've noticed that if any of sensors configured in air-visual-card is unavailable (does not exist in HA registry) whole view crashes - becomes blank.

this is my sample config:
```yaml
- air_pollution_level: sensor.u_s_air_pollution_level
   air_quality_index: sensor.u_s_air_quality_index
   city: Warszawa
   hide_title: true
   main_pollutant: sensor.u_s_main_pollutant
   temp: weather.dark_sky
   type: 'custom:air-visual-card'
```

when the problem occours there is an exception in browser console
```
Uncaught TypeError: Cannot read property 'attributes' of undefined
    at HTMLElement.set hass [as hass] (air-visual-card.js:235)
    at HTMLElement._createCardElement (hui-stack-card.ts:79)
    at HTMLElement._rebuildCard (hui-stack-card.ts:96)
    at HTMLElement.t.addEventListener.once (hui-stack-card.ts:85)
    at r (fire_event.ts:76)
    at create-card-element.ts:111
```
