### ISSUE TITLE
FEATURE REQUEST: Add more sensors

### ISSUE THREAD

**Issue by MimbaMonkeyHouse** [dnguyen800/air-visual-card#16]
Love this. Just had to hack a little the main pollutant sensor for PM2.5:
```
sensor:
  - platform: template
    sensors:
      main_pollutant:
        unit_of_measurement: 'µg/m3'
        value_template: "{{ states('sensor.pm_2_5um') | round(1) }}"
        attribute_templates:
          pollutant_symbol: p2
          pollutant_unit: µg/m3
          lati: -10.5647
          long: 135.98975
```
This allows to get around the free plan limitation. A better value template could be created to change the value based on the sensor.us_main_pollutant...
Anyways, it would be great to use this same card to display more sensons. PM<10 and PM<1 are no brainers, but others may want SO2 or CO as well. Additional sensors could be displayed below the main pollutant...
