### ISSUE TITLE
Rendering of dashboard in HA fails when one of sensors is not given

### ISSUE THREAD

**Issue by artospaj** [dnguyen800/air-visual-card#30]
I noticed hat bug in HA v108.9, I believe it existed before but didn't stop the rendering of the whole HA dashboard.

![AirVisualCard - TypeError - HA v106 6](https://user-images.githubusercontent.com/11021356/83500225-c68b9780-a4be-11ea-8aa0-2f7aff684f7a.png)

My Lovelace configuration for card:
```yaml
      - type: custom:air-visual-card
        air_quality_index: sensor.purifier_pro_aqi
        main_pollutant: sensor.purifier_pro_aqi
        hide_title: true
        icons: /local/air-visual-card/
```

As you can see there is no `air_pollution_level` sensor provided (it's optional in docs), but looking at the code if any of sensors is not provided, will make JS fail in the same place.

(fix in the way, I'll reference this issue)
