### ISSUE TITLE
Feature Request: Option to hide the icon

### ISSUE THREAD

**Issue by ChrisRomp** [dnguyen800/air-visual-card#34]
Would be nice to not see the face (or any icon) optionally.

Suggested parameter: `show_icon`
Type: `boolean`
Default value: `true`

Then in the configuration, one could have:

```yaml
  - type: 'custom:air-visual-card'
    air_pollution_level: sensor.use_the_actual_name_of_your_sensor_not_this_example
    air_quality_index: sensor.use_the_actual_name_of_your_sensor_not_this_example
    main_pollutant: sensor.use_the_actual_name_of_your_sensor_not_this_example
    temp: weather.use_the_actual_name_of_your_weather_entity_not_this_example
    city: 'San Francisco'
    show_icon: false
````
