### ISSUE TITLE
Top left corner do not round

### ISSUE THREAD

**Issue by yuvalabou** [dnguyen800/air-visual-card#39]
![image](https://user-images.githubusercontent.com/3170485/99577384-ee76a500-29e3-11eb-8af9-d05bf0236ea4.png)

The top left corner is not aware of the radius set by the theme..

```yaml
      - type: custom:air-visual-card
        hide_title: true
        air_pollution_level: sensor.u_s_air_pollution_level
        air_quality_index: sensor.u_s_air_quality_index
        main_pollutant: sensor.u_s_main_pollutant
```
