### ISSUE TITLE
No other cards are visible after I added this card 

### ISSUE THREAD

**Issue by digidestination** [dnguyen800/air-visual-card#55]
After I added this card, this and all other cards disappear.

**Comment by Swampen** [comment]
Can you add your card configuration and any errors in the dev console (F12)

**Comment by jaruba** [comment]
@Swampen it's likely that me and @digidestination have the same issue

i recently updated ha and all the extensions including this one, under Overview -> Home i can see all the cards when i refresh the page, but while browsing around ha, the next time i get to Overview there are no cards at all..

dev tools shows this as the only error in lovelance:
```
air-visual-card.js?hacstag=157674859200:426 Uncaught TypeError: Cannot read properties of undefined (reading 'attributes')
    at HTMLElement.set hass [as hass] (air-visual-card.js?hacstag=157674859209:426)
    at HTMLElement.value (hui-masonry-view.ts:44)
    at HTMLElement.value (hui-masonry-view.ts:44)
    at HTMLElement.t.addEventListener.once (hui-masonry-view.ts:44)
    at i (typography.js:181)
    at ha-logbook.ts:28
```
which points to this line: https://github.com/dnguyen800/air-visual-card/blob/master/dist/air-visual-card.js#L426


and my config is:
```
type: custom:vertical-stack-in-card
title: Air Quality
cards:
  - type: custom:air-visual-card
    air_pollution_level: sensor.u_s_air_pollution_level_2
    air_quality_index: sensor.u_s_air_quality_index_2
    main_pollutant: sensor.u_s_main_pollutant_2
    city: Bucharest
    hide_title: true
    hide_weather: true
```

this error makes no sense to me though, as i don't set the `weather` property:
https://github.com/dnguyen800/air-visual-card/blob/master/dist/air-visual-card.js#L256

which means that `weatherEntity` should be `''`, so this should be falsey:
https://github.com/dnguyen800/air-visual-card/blob/master/dist/air-visual-card.js#L425

and thus the code should never reach the 426th line which is where the error is from
