### ISSUE TITLE
Card does not show 2 of 3 sensors

### ISSUE THREAD

**Issue by dankarization** [dnguyen800/air-visual-card#61]
This is my config
```
      - type: custom:air-visual-card
        air_pollution_level: sensor.u_s_air_pollution_level
        air_quality_index: sensor.u_s_air_quality_index
        main_pollutant: sensor.u_s_main_pollutant
        weather: weather.my_weather
        hide_weather: true
        hide_title: true
        unit_of_measurement: AQI
        hide_face: false
```

And this is how card looks
![image](https://github.com/dnguyen800/air-visual-card/assets/26330178/7e980c6c-bdf0-4307-a940-e2273e4cb368)
When I click on 2 empty spaces, 2 working sensors opens accordingly
![image](https://github.com/dnguyen800/air-visual-card/assets/26330178/01e20960-68d9-4b0a-ba40-966fe5099050)
![image](https://github.com/dnguyen800/air-visual-card/assets/26330178/4256b43e-a520-49b7-9f41-b484ba127065)

What am I doing wrong here? HA version 2024.4.3

**Comment by dnguyen800** [comment]
I'll keep this issue open until it is tested furthered. The issue is still present for me but maybe it is fixed for others.

**Comment by asifkassam** [comment]
Try using

air_pollution_level: sensor.u_s_air_quality_index

**Comment by dankarization** [comment]
With no changes to the config now the card shows main pollutant but not it's level
![image](https://github.com/dnguyen800/air-visual-card/assets/26330178/67b1938a-8700-4a9b-a765-fb279d1730de)
With changes @asifkassam suggested now everything looks good, thanks!
![image](https://github.com/dnguyen800/air-visual-card/assets/26330178/53ade8e7-ee66-4a2e-8a45-9687fc6a7a6f)

But it's counter intuitive for me that I need to input index instead of level there to see level hehe. Calculations are done by the card itself now?

**Comment by anthonws** [comment]
This is not working for me for a while and the latest fix did not help.
Not sure if its the station I'm using, but it seems that the data is there.

<img width="1668" alt="image" src="https://github.com/dnguyen800/air-visual-card/assets/181357/83326ca4-5756-417c-9af9-16d7d83e5494">
<img width="1696" alt="image" src="https://github.com/dnguyen800/air-visual-card/assets/181357/a985b372-adc2-46e1-9e9f-f7418de35bb3">

```
cards:
  - type: custom:air-visual-card
    hide_weather: true
    hide_title: true
    hide_face: false
    air_pollution_level: sensor.waqi_olivais_lisboa_portugal
    air_quality_index: sensor.waqi_olivais_lisboa_portugal
    main_pollutant: sensor.olivais_lisboa_portugal_dominant_pollutant
    unit_of_measurement: AQI
```

<img width="479" alt="image" src="https://github.com/dnguyen800/air-visual-card/assets/181357/750c7f31-0c9f-4ada-b914-9b6f9277b28e">
